### ISSUE TITLE
Dropdown archive for individual comics

### ISSUE THREAD

**Issue by sbboard** [Frumph/comic-easel#14]
I was hoping for a dropdown archive listing individual comic posts for quick navigation.
Also, a dropdown listing all the comics only within the currently chapter would be a nice option as well.
Thanks!!

**Comment by Frumph** [comment]
added, but only works currently in the comic sidebars, going to add it to the default navigation soon

**Comment by Frumph** [comment]
done -> working

**Comment by sbboard** [comment]
Thanks!! I love you!!
