### ISSUE TITLE
Random Comic Widget not random

### ISSUE THREAD

**Issue by hijinksensue** [Frumph/comic-easel#17]
Seems to almost always show the most recent comic.

**Comment by Frumph** [comment]
if you're using wp-supercache put this word in the exclude box:   random

**Comment by Frumph** [comment]
http://code.tutsplus.com/articles/configuring-w3-total-cache-advanced-page-cache-ii--cms-21159

part 10 and 11 if you're using w3tc cache to 'exclude' pages

**Comment by hijinksensue** [comment]
The exclude box isn't an option. There's a box to non-cached strings that reads: 

Add here strings (not a filename) that forces a page not to be cached. For example, if your URLs include year and you dont want to cache last year posts, it’s enough to specify the year, i.e. ’/2004/’. WP-Cache will search if that string is part of the URI and if so, it will not cache that page.

Putting "random" minus the quotes in this box has no effect.

**Comment by hijinksensue** [comment]
Just bumping this to make sure you know the issue is still active.

**Comment by Frumph** [comment]
[x] Don’t cache pages with GET parameters. (?x=y at the end of a url)

Is that checkmarked in the wp-supercache settings? if not, checkmark it and clear cache

**Comment by Frumph** [comment]
okay, well you wrote 'widget' up in the title and my brain totally ignored it ;/   

Looking at the rand in the widget code now ;/ sorry!

**Comment by Frumph** [comment]
Can I get a screenshot of the options that you have set inside of the widget from appearance -> widget and you uncollapsing the widget?

**Comment by hijinksensue** [comment]
D'oh. "Random Thumbnail" was unchecked. This seems like it shouldn't even be an option in the "Random Comic Widget." It seems like it would make more sense if "get first in chapter*" *This overrides random... was an option, but showing a random thumbnail was always the default. It's working now. You can close this ticket.

**Comment by Frumph** [comment]
heh I rewrote the whole query part anyways ;)   it needed it  https://github.com/Frumph/comic-easel/commit/8a684c8440008a6cf4cea8b4d65394adf0e2278b  anyways ;)

glad to know it was something simple though ya

**Comment by Frumph** [comment]
and and it's not a random comic widget, that's just the title you put there, it's the 'thumbnail' widget ;/
