### ISSUE TITLE
According to GlotPress, CE is "not properly prepared for localization" (failed import)

### ISSUE THREAD

**Issue by JN-Squire** [Frumph/comic-easel#23]
So I discovered [GlotPress](https://translate.wordpress.org/) and figured it would be much easier to create and maintain [localizations of the plugin with this tool](https://translate.wordpress.org/projects/wp-plugins/comic-easel) (for now). But it displays the following error:
![image](https://cloud.githubusercontent.com/assets/818639/21501639/c5542806-cc49-11e6-8f5b-b84b36c31c44.png)

The [help page](https://make.wordpress.org/meta/handbook/documentation/translations/#this-plugin-is-not-properly-prepared-for-localization-%e2%80%93-help) says "it usually means that something is wrong with the text domain" and talks about getting details through a Slack channel. 

So in order to solve this bug, I suggest we get  first the details of the failed import @Frumph : do you think you could do it? It would be really helpful.

**Comment by Frumph** [comment]
Does it say "why" it doesn't think it's not properly prepared for localization .. cause codestyle localization is loading it just fine

**Comment by JN-Squire** [comment]
Yes it does.
I just figured how to find the info in the #meta-language-packs channel in the WlordPress Slack group. Here is the screenshot of what happened at the import:
![slack_2017-02-24_15-55-39](https://cloud.githubusercontent.com/assets/818639/23307985/dbacdcc2-faa9-11e6-81e0-f3a04940f875.png)

It looks like to needs a special kind of text domain declaration in the file header.

According to the [Translations FAQ](https://make.wordpress.org/meta/handbook/documentation/translations/#how-do-i-internationalize-my-plugin-how-do-i-set-a-text-domain),

> Please follow the instructions in the plugin developer handbook to internationalize all your strings, **taking careful note to have a “Text Domain:” in your plugin header that matches the slug of your plugin**.

So fixing this bug probably implies to change the "Text Domain" in ComicEasel plugin header in order to match the slug of the plugin (probably "comic-easel"?).

**Comment by Frumph** [comment]
Okay, will add.

**Comment by JN-Squire** [comment]
@Frumph  There, I [edited the files](https://github.com/Frumph/comic-easel/commit/b3e3f01c6da68e073f5166e90131b723e1ced125).  Now we will only know if the requirements are meet once it gets imported in the WordPress repository.

**Comment by Frumph** [comment]
added to github, seemed it didnt stick
