### ISSUE TITLE
Can't use function return value in write context

### ISSUE THREAD

**Issue by kmvoorhees** [Frumph/comic-easel#29]
My friend is getting the following error on her website using this plugin:

`Fatal error: Can't use function return value in write context in /home1/creatrix/public_html/wp-content/plugins/comic-easel/comiceasel.php on line 609`

I'm afraid I'm not very familiar with the functions in question but the examples in this article appear to be similar to the code in question:

https://mycyberuniverse.com/how-fix-cant-use-function-return-value-write-context.html

**Comment by Frumph** [comment]
this was fixed in an emergency patch, go to go to the plugins, remove comic easel then get comic easel from the repo again and it will have the fix in it
