### ISSUE TITLE
Is this project still active?

### ISSUE THREAD

**Issue by kmhcreative** [Frumph/comic-easel#34]
Hey Philip, I see that the plugin was de-listed in January from the WordPress Plugin Directory for an unspecified "Security Issue" and there haven't been any releases of either the plugin or theme, either here or there, in quite a while (years).  I'm just wondering if you're still actively developing the Comic Easel plugin or ComicPress theme or not?

**Comment by Frumph** [comment]
Yeah, still supporting it;  classicpress instead of wordpress though
https://www.classicpress.net/get-classicpress/
