### ISSUE TITLE
Widget Logic, to include child chapters

### ISSUE THREAD

**Issue by thirdpotato** [Frumph/comic-easel#6]
Hello, I'd like to have widget logic work to check children chapters as well if you put in the single ID # of the chapter.

I have one chapter on my site that I create an infinite many numbers of child chapters for. It's becoming a pain to have to manually add every child chapter in the widgets in which I want them to appear. 

Like the chapter I want this widget to apply to is called: "Scenes"
Currently there are no posts in Scenes, but there are multiple Child Chapters with posts in them inside of Scenes.
I want the widget to apply to everything in Scenes and its subchapters when I type ceo_is_chapter('scenes')

**Comment by Frumph** [comment]
ceo_test_is_chapter_in_story($story_id = 0)

did you try that function yet?  uses the ID not the slug
