### ISSUE TITLE
Link to comments in navigation does not show number for current page

### ISSUE THREAD

**Issue by EmilyRyan** [Frumph/comic-easel#8]
In the Comic Easel config there is an option that I left activated:

<strong>Enable the comment link in the comic navigation?</strong>
When this is enabled, a link will appear in the navigation that lets you go to the comments section of the current post, it also shows how many comments there currently are. 

Problem is, on each comic page of my site except the main page, the parenthesized number shows the total amount of comments I have received (2) on a different page, this one: http://emilyryan.se/gramarye/comic/the-roster-of-names/ 

Whether this is a bug or me setting up the URL:s wrong I can't say, but I thought I'd report it just in case.

**Comment by Frumph** [comment]
Still an issue?

**Comment by EmilyRyan** [comment]
Yeah... no change. I don't know what to do. 
http://emilyryan.se/gramarye/comic/the-roster-of-names/#comments isn't perfect either, the comments in the next, previous navigation should show (2).

**Comment by Frumph** [comment]
unless two of them are pingbacks and not displayed

**Comment by EmilyRyan** [comment]
No, I'm almost certain they aren't, or rather, it would be an incredible coincidence. Comments (4) is displayed on every page except the starting page. It is the total number of comments that I have on comic pages in total. 
Page with zero comments showing (4): http://emilyryan.se/gramarye/comic/trail-of-seals/
Page with two comments showing (4): http://emilyryan.se/gramarye/comic/the-sheep-rises/

**Comment by Frumph** [comment]
Your theme has a filter on it.

/core/includes/functions-extras.php

line: 67
add_filter( 'get_comments_number', 'responsive_comment_count', 0 );

if you encapsulate that line with /*  */   (or) two //  slashes in front of it to comment it out from running, tell me if it still happens

The function it runs is written wrong:
`
function responsive_comment_count( $count ) {
	if ( !is_admin() ) {
		global $id;
		$comments         = get_comments( 'status=approve&post_id=' . $id );
		$comments_by_type = separate_comments( $comments );

		return count( $comments_by_type['comment'] );
	} else {
		return $count;
	}
}
`

That should be global $post; and &post_id=' . $post->ID   

Cause $id can't be guaranteed to have the right value inside of it with everything going on in a page, should not be used in this method

**Comment by Frumph** [comment]
also (in addition to)
```
if (!is_admin() && in_the_loop()) {
``` 
would make it so it only runs on sections that are 'in the main loop'

**Comment by EmilyRyan** [comment]
I commented out line 67 and added  && in_the_loop(). It works like a charm! 
Thank you for the help, I would never have found it myself! Looking through other people's themes is beyond what anyone would hope for, so thank you.

**Comment by Frumph** [comment]
$post and $post->ID replacing $id  one and in_the_loop()    is the fix ..

the commenting out the line only tests if that was where the problem was ;)

sorry I didn't make myself clearer heh

**Comment by EmilyRyan** [comment]
This is what I did, everything seems to work:
```
function responsive_comment_count( $count ) {
	if ( !is_admin() && in_the_loop()) {
		global $post;
		$comments         = get_comments( 'status=approve&post_id=' . $post->ID );
		$comments_by_type = separate_comments( $comments );

		return count( $comments_by_type['comment'] );
	} else {
		return $count;
	}
}
```

**Comment by Frumph** [comment]
yeah but if you comment out line 67 it won't even run that ;/  so try it without 67 commented out if it breaks it again, recomment

**Comment by EmilyRyan** [comment]
Forgot to say; I also removed the comment!

**Comment by Frumph** [comment]
\o/ yay hehe
